[project]
name = 'Decentralized-Consciousness-Evolution-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cognitive-enhancement-tokenization]
path = 'contracts/cognitive-enhancement-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-level-certification]
path = 'contracts/consciousness-level-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.mind-expansion-experience-verification]
path = 'contracts/mind-expansion-experience-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
